# Symboard CircleCI 2.0 config file

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: Install python dependencies in a venv.
          command: |
            ls
            sudo pip install poetry
            #poetry shell
            poetry install
      - run:
          name: Run unit tests with coverage
          command: |
            poetry run nosetests -v --with-coverage --cover-package=symboard --cover-erase
      - store_artifacts:
          path: htmlcov

  deploy:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - run: ls
