# Symboard CircleCI 2.0 config file

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: Install python dependencies in a venv.
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            python3 -m unittest discover -v


