# Symboard CircleCI 2.0 config file

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: Install python dependencies in a venv.
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run unit tests
          command: |
            pipenv run python3 -m unittest discover -v


